<h1><?php echo $this->translate("Perte du mot de passe de Murloc-avenue !"); ?></h1>
<br />
<br />
<div class='row'>
    <div class='col-md-6'>
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->translate("Vous avez perdu votre mot de passe? Aucun probleme !
                    Rentrer votre email et un courrier vous sera envoyé afin de lancer la procédure de changement de mot de passe."); ?></h3>
            </div><!-- /.box-header -->
            <!-- form start -->
            <form role="form" action='<?php echo $this->url('users-pwdswap'); ?>' method='post'>
                <div class="box-body">
                    <div class="form-group">
                        <label for="email"><?php echo $this->translate("Adresse email") ?></label>
                        <input type="email" class="form-control" name='mail' id="email" placeholder="<?php echo $this->translate('Enter email'); ?>">
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary"><?php echo $this->translate("Soumettre") ?></button>
                </div>
            </form>
        </div>
    </div>
    <div class='col-md-6'>

    </div>
</div>