<?php

return array(
    'classes' => array(
        0 => 'Inconnue',
        1 => 'Chevalier de la mort',
        2 => 'Druide',
        3 => 'Chasseur',
        4 => 'Mage',
        5 => 'Paladin',
        6 => 'Prêtre',
        7 => 'Voleur',
        8 => 'Chaman',
        9 => 'Démoniste',
        10 => 'Guerrier',
        11 => 'Moine',
    ),
    'couleur_classes' => array(
        0 => '#FFF',
        1 => '#C41F3B',
        2 => '#FF7C0A',
        3 => '#AAD372',
        4 => '#68CCEF',
        5 => '#F48CBA',
        6 => '#FFFFFF',
        7 => '#FFF468',
        8 => '#1a3caa',
        9 => '#9382C9',
        10 => '#C69B6D',
        11 => '#00C77B',
    ),
    'races' => array(
        0 => 'Inconnue',
        1 => 'Gnome',
        2 => 'Humain',
        3 => 'Nain',
        4 => 'Elfe de la nuit',
        5 => 'Troll',
        6 => 'Mort-vivant',
        7 => 'Orque',
        8 => 'Tauren',
        9 => 'Draenei',
        10 => 'Elfe de sang',
        11 => 'Worgen',
        12 => 'Goblin',
        13 => 'Pandaren',
    ),
    'roles' => array(
        0 => 'Inconnu',
        1 => 'Tank',
        2 => 'Soigneur',
        3 => 'Melée',
        4 => 'Distance',
    ),
    'factions' => array(
        0 => 'Inconnue',
        1 => 'Alliance',
        2 => 'Horde',
    ),
);

