<h1><?php echo $this->translate("Ajouter un jeu"); ?></h1>
<form method='post' action="<?php echo $this->url('jeux-add', array('action' => 'add')) ?>" class="form-inline">
    <fieldset>
        <div class="control-group">
            <label class="control-label"><?php echo $this->translate("Nom"); ?></label>
            <div class="controls">
                <input type='text' name="nom" required="true"/>
            </div>
            <label class="control-label"><?php echo $this->translate("Logo"); ?></label>
            <div class="controls">
                <input type='text' name="logo" required="true"/>
            </div>
            <div class="form-actions">
                <input type='submit' value='submit' class="btn"/>
            </div>
    </fieldset>
</form>