<?php
$this->headScript()
        ->prependFile($this->basePath('dist/js/pages/dashboard.js'));
if (!empty($this->err)):
    ?>
    <div class="box box-danger box-solid">
        <div class="box-header with-border">
            <h5>Une erreur est survenue !</h5>
            <div class='box-tools pull-right'>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class='box-body'>
            <ul>
                <?php foreach ($this->err as $r): ?>
                    <li><?php echo $this->translate($r); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
<?php if (!empty($this->info)): ?>
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h5>Félicitation !</h5>
            <div class='box-tools pull-right'>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class='box-body'>
            <ul>
                <?php foreach ($this->info as $r): ?>
                    <li><?php echo $this->translate($r); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
<h1>test</h1>
<a href="<?php echo $this->url('guildes-add'); ?>">Créer une guilde</a>
<ul>

    <?php foreach ($this->guildes as $g): ?>
        <li><?php echo $g['guildeNom']; ?> / <?php echo $g['guildeServeur']; ?> / nom jeux <?php echo $g['nomJeux']; ?></li>
    <?php endforeach; ?>




    <table clas ="table table-bordered table-striped           table-hover">
        <tr>
            <th>nom</th>
            <th>serveur</th>
            <th>jeux</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($this->guildes as $guilde) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($guilde['guildeNom']); ?></td>
                <td><?php echo $this->escapeHtml($guilde['guildeServeur']); ?></td>
                <td><?php echo $this->escapeHtml($guilde['nomJeux']); ?></td>
                <td>
                    <a class="btn btn-info" href="">
                        <span class="glyphicon glyphicon-pencil"></span>&nbsp;Edit</a>
                    <a class="btn btn-danger" href="">
                        <span class="glyphicon glyphicon-trash">
                        </span>&nbsp;Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td colspan="5"> <a class="btn btn-success pull-right" href="<?php echo $this->url('guildes-add', array('action' => 'add')); ?>"><span clas ="glyphicon glyphicon-plus-sign">
                    </span>&nbsp;
                    Add new User&nbsp;<span
                        class="glyphicon glyphicon-user"></span></a>
            </td>
        </tr>
    </table>

</ul>