<h1><?php echo $this->translate("Liste des jeux") ?></h1>

<table class="table table-bordered table-striped table-hover">
    <tr>
        <th><?php echo $this->translate("nom") ?></th>
        <th><?php echo $this->translate("logo") ?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->jeux as $jeu) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($jeu['nom']); ?></td>
            <td><?php echo $this->escapeHtml($this->translate($jeu['logo'])); ?></td>
            <td>
                <a class="btn btn-info disabled" href=""><span class="glyphicon glyphicon-pencil "></span>&nbsp;<?php echo $this->translate("Modifier") ?></a>
                <a class="btn btn-danger disabled" href=""><span class="glyphicon glyphicon-trash "></span>&nbsp;<?php echo $this->translate("Supprimer") ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td colspan="4"> <a class="btn btn-success pull-right" href="<?php echo $this->url('jeux-add'); ?>"><span clas ="glyphicon glyphicon-plus-sign">
                </span>&nbsp;<?php echo $this->translate("Créer un jeu") ?>&nbsp;<span class="glyphicon glyphicon-user"></span></a>
        </td>
    </tr>
</table>

</ul>