<?php
$this->headScript()
        ->prependFile($this->basePath('dist/js/pages/dashboard.js'));
if (!empty($this->err)):
    ?>
    <div class="box box-danger box-solid">
        <div class="box-header with-border">
            <h5>Une erreur est survenue !</h5>
            <div class='box-tools pull-right'>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class='box-body'>
            <ul>
                <?php foreach ($this->err as $r): ?>
                    <li><?php echo $this->translate($r); ?></li>
    <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
<?php if (!empty($this->info)): ?>
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h5>Félicitation !</h5>
            <div class='box-tools pull-right'>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class='box-body'>
            <ul>
                <?php foreach ($this->info as $r): ?>
                    <li><?php echo $this->translate($r); ?></li>
    <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
<h1>Récupération du mot de passe de Murloc-avenue !</h1>
<br />
<br />
<div class='row'>
    <div class='col-md-8'>
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Bonjour <?php if (isset($this->pseudo)) echo $this->pseudo; ?></h3>
            </div>
            <div class="box-body">
                <?php if (isset($this->pseudo) && empty($this->info)): ?>
                    <form role="form" action='<?php echo $this->url('users-changepassword'); ?>' method='post'>
                        <div class="box-body">
                            <div class="form-group">
                                <label for="passOne" class="col-sm-4 control-label">Nouveau mot de passe :</label>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control"  name='pwd' id="passOne" placeholder="Password" required>
                                </div>
                            </div><div class="form-group">
                                <label for="passTwo" class="col-sm-4 control-label">Confirmation du mot de passe:</label>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control"  name='pwdConfirm' id="passTwo" placeholder="Password" required>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer">
                            <input type="hidden" name="forgetkey" value="<?php echo $this->forgetkey;?>" />
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                <?php endif; ?>
                <?php if (empty($this->err) && !empty($this->info)): ?>
                    <p> Vous pouvez maintenant vous connectez ! </p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>