<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Guildes\Module'                      => __DIR__ . '/Module.php',
    'Guildes\Controller\GuildeController' => __DIR__ . '/src/Guildes/Controller/GuildeController.php',
    'Guildes\Service\Guildes'             => __DIR__ . '/src/Guildes/Service/Guildes.php',
);
