<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Jeux\Module' => __DIR__ . '/Module.php',
    '\Jeux\View\Helper\JeuxHelper' => __DIR__ . '/src/Jeux/View/Helper/JeuxHelper.php',
);
