<?php

return array('application/contact/index' => __DIR__ . '/view/application/contact/index.phtml',
    'application/index/index' => __DIR__ . '/view/application/index/index.phtml',
    'backend/index/index' => __DIR__ . '/view/backend/index/index.phtml',
    'backend/plugin/ajax-list' => __DIR__ . '/view/backend/plugin/ajax-list.phtml',
    'backend/plugin/create' => __DIR__ . '/view/backend/plugin/create.phtml',
    'backend/plugin/list' => __DIR__ . '/view/backend/plugin/list.phtml',
    'backend/plugin/update' => __DIR__ . '/view/backend/plugin/update.phtml',
    'error/404' => __DIR__ . '/view/error/404.phtml',
    'error/index' => __DIR__ . '/view/error/index.phtml',
    'guildes/guilde/add' => __DIR__ . '/view/guildes/guilde/add.phtml',
    'guildes/guilde/edit' => __DIR__ . '/view/guildes/guilde/edit.phtml',
    'guildes/guilde/index' => __DIR__ . '/view/guildes/guilde/index.phtml',
    'guildes/guilde/remove' => __DIR__ . '/view/guildes/guilde/remove.phtml',
    'layout/app/head' => __DIR__ . '/view/layout/app/head.phtml',
    'layout/app/header' => __DIR__ . '/view/layout/app/header.phtml',
    'layout/app/messages' => __DIR__ . '/view/layout/app/messages.phtml',
    'layout/app/sidebar' => __DIR__ . '/view/layout/app/sidebar.phtml',
    'layout/backend/breadcrumbs' => __DIR__ . '/view/layout/backend/breadcrumbs.phtml',
    'layout/backend/head' => __DIR__ . '/view/layout/backend/head.phtml',
    'layout/backend/header' => __DIR__ . '/view/layout/backend/header.phtml',
    'layout/backend/messages' => __DIR__ . '/view/layout/backend/messages.phtml',
    'layout/backend/navbar' => __DIR__ . '/view/layout/backend/navbar.phtml',
    'layout/backend' => __DIR__ . '/view/layout/backend.phtml',
    'layout/layout' => __DIR__ . '/view/layout/layout.phtml',
    'layout/ajax' => __DIR__ . '/view/layout/ajax.phtml',
    'partial/commun/breadcrumbs' => __DIR__ . '/view/partial/commun/breadcrumbs.phtml',
    'partial/commun/menu-item' => __DIR__ . '/view/partial/commun/menu-item.phtml',
    'partial/form-partial' => __DIR__ . '/view/partial/form-partial.phtml',
    'users/index/forgetpwd' => __DIR__ . '/view/users/index/forgetpwd.phtml',
    'users/index/querypwdswap' => __DIR__ . '/view/users/index/querypwdswap.phtml',
);
