<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                       => __DIR__ . '/Module.php',
    'Application\Controller\ContactController' => __DIR__ . '/src/Application/Controller/ContactController.php',
    'Application\Controller\IndexController'   => __DIR__ . '/src/Application/Controller/IndexController.php',
);
