<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module' => __DIR__ . '/Module.php',
    'Application\Service\LogService' => __DIR__ . '/src/Application/Service/LogService.php',
    'Application\Helper\Messages' => __DIR__ . '/src/Application/Helper/Messages.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
);
