<h1><?php echo $this->translate("Liste des guildes") ?></h1>

<table class="table table-bordered table-striped           table-hover">
    <tr>
        <th><?php echo $this->translate("nom") ?></th>
        <th><?php echo $this->translate("serveur") ?></th>
        <th><?php echo $this->translate($this->translate("jeux")); ?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->guildes as $guilde) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($guilde['guildeNom']); ?></td>
            <td><?php echo $this->escapeHtml($this->translate($guilde['guildeServeur'])); ?></td>
            <td><?php echo $this->escapeHtml($this->translate($guilde['nomJeux'])); ?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('guildes-edit', array('id' => $guilde['guildeId'])); ?>"><span class="glyphicon glyphicon-pencil "></span>&nbsp;<?php echo $this->translate("Modifier") ?></a>
                <a class="btn btn-danger" href="<?php echo $this->url('guildes-del', array('id' => $guilde['guildeId'])); ?>"><span class="glyphicon glyphicon-trash "></span>&nbsp;<?php echo $this->translate("Supprimer") ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td colspan="4"> <a class="btn btn-success pull-right" href="<?php echo $this->url('guildes-add'); ?>"><span clas ="glyphicon glyphicon-plus-sign">
                </span>&nbsp;<?php echo $this->translate("Créer une guilde") ?>&nbsp;<span class="glyphicon glyphicon-user"></span></a>
        </td>
    </tr>
</table>

</ul>