<meta charset="utf-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php echo $this->headTitle('Murloc Avenue : DEV') ?>
<?php
echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>
<!-- Le styles -->
<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/defaut/img/favicon.ico'))
        ->prependStylesheet($this->basePath('/defaut/css/Application/AdminLTE.css'))
        ->prependStylesheet($this->basePath('/defaut/css/Application/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/defaut/css/Application/zf-table.css'))
?>
<!-- Scripts -->
<?php
echo $this->headScript()
        ->prependFile($this->basePath('/defaut/js/Application/zf-table.js'))
        ->prependFile($this->basePath('/defaut/js/Application/messages_fr.min.js'))
        ->prependFile($this->basePath('/defaut/js/Application/jquery.validate.min.js'))
        ->prependFile($this->basePath('/defaut/js/Application/app.js'))
        ->prependFile($this->basePath('/defaut/js/Application/bootstrap.min.js'))
        ->prependFile($this->basePath('/defaut/js/Application/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('/defaut/js/Application/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('/defaut/js/Application/jquery-ui.min.js'))
        ->prependFile($this->basePath('/defaut/js/Application/jQuery-2.1.4.min.js'));
?>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />

<!-- HTML5 shim, pour le support IE6-8 support des éléments HTML5  -->
<!--[if lt IE 9]>
    <script src="<?= $this->basePath('/defaut/js/Application/html5shiv.js') ?>"></script>
<![endif]-->