<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Backend\Module'                                   => __DIR__ . '/Module.php',
    'Backend\Controller\GuildesController'             => __DIR__ . '/src/Backend/Controller/GuildesController.php',
    'Backend\Controller\IndexController'               => __DIR__ . '/src/Backend/Controller/IndexController.php',
    'Backend\Controller\JeuxController'                => __DIR__ . '/src/Backend/Controller/JeuxController.php',
    'Backend\Controller\PersonnagesController'         => __DIR__ . '/src/Backend/Controller/PersonnagesController.php',
    'Backend\Controller\PluginController'              => __DIR__ . '/src/Backend/Controller/PluginController.php',
    'Backend\Controller\RosterController'              => __DIR__ . '/src/Backend/Controller/RosterController.php',
    'Backend\Controller\RosterHasPersonnageController' => __DIR__ . '/src/Backend/Controller/RosterHasPersonnageController.php',
);
