<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Users\Module'                     => __DIR__ . '/Module.php',
    'Users\Controller\IndexController' => __DIR__ . '/src/Users/Controller/IndexController.php',
    'Users\Model\Users'                => __DIR__ . '/src/Users/Model/Users.php',
);
