<h1><?php echo $this->translate("Création d'une guilde") ?></h1>
<form method='post' action="<?php echo $this->url('guildes-add', array('action' => 'add')) ?>" class="form-inline">
    <fieldset>
        <div class="control-group">
            <label class="control-label"><?php echo $this->translate("Nom") ?></label>
            <div class="controls">
                <input type='text' name="nom" required="true" value="<?php echo $guilde['nom']; ?>"/>
            </div>
            <label class="control-label"><?php echo $this->translate("Serveur") ?></label>
            <div class="controls">
                <input type='text' name="serveur" required="true" value="<?php echo $guilde['serveur']; ?>"/>
            </div>
            <label class="control-label"><?php echo $this->translate("Jeux") ?></label>
            <div class="controls">
                <select name="jeux" >
                    <?php foreach ($this->jeux as $j): ?>
                        <option <?php if ($guilde['idJeux'] == $j['idJeux']) echo 'selected="selected"'; ?> value="<?php echo $j['idJeux']; ?>"><?php echo $this->translate($j['nom']); ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <p class="help-block">test aide</p>
            <div class="form-actions">
                <input type='submit' value='submit' class="btn"/>
            </div>
    </fieldset>
</form>