<?php
echo $this->plugin('doctype')->setDoctype(\Zend\View\Helper\Doctype::HTML5);
?>
<html lang="en">
    <head>
        <?= $this->render('layout/backend/head') ?>
    </head>
    <body>
        <h1>Theme 1</h1>
        <?= $this->render('layout/backend/header') ?>
        <div class="container">
            <?= $this->render('layout/backend/breadcrumbs') ?>
            <?= $this->render('layout/app/messages') ?>
            <?= $this->content ?>
        </div>
        <?= $this->plugin('InlineScript'); ?>
    </body>
</html>
